<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTddFvns\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTddFvns/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTddFvns.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTddFvns\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTddFvns\App_KernelDevDebugContainer([
    'container.build_hash' => 'TddFvns',
    'container.build_id' => 'f75c10f7',
    'container.build_time' => 1610473473,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTddFvns');
